##
## This file was generated by Google::ProtocolBuffers (0.08)
## on Sat Aug 21 20:34:41 2010
##      
use strict;
use warnings;
use Google::ProtocolBuffers;
{       
    unless (Grids::Message->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Grids::Message',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'event', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'id', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'signed_message_id', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'source', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'destination', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_UINT64(), 
                    'timestamp', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_UINT64(), 
                    'expires', 7, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Grids::Message::Echo->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Grids::Message::Echo',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(), 
                    'Grids::Message', 
                    'base', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(), 
                    Google::ProtocolBuffers::Constants::TYPE_STRING(), 
                    'echo_string', 2, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

}
1;
