/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of OTR.xs. Do not edit this file, edit OTR.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "OTR.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "crypt-otr.h"

#include "ppport.h"


/* Global Data */

#define MY_CXT_KEY "Crypt::OTR::_guts" XS_VERSION

typedef struct {
    /* Put Global Data in here */
    OtrlUserState userstate;		/* you can access this elsewhere as MY_CXT.userstate */
	char* keyfile;
	char* fprfile;
	char* accountname; /* This is YOUR id.  OTR convention is that *username* is THEM */
	char* protocol;
	int* max_message_size;
	char* inject_cb; /* From this callback you get an encrypted version of your original message (sort of) */
	char* display_cb; 
	char* connected_cb; /* This callback is called when a context transitions to ENCRYPTED */
	char* disconnected_cb; /* This callback is called when a context transitions to PLAINTEXT */ 
	char* error_cb;
	char* warning_cb;
	char* info_cb;
	char* new_fpr_cb;
} my_cxt_t;

START_MY_CXT

#include "const-c.inc"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 50 "OTR.c"

/* INCLUDE:  Including 'const-xs.inc' from 'OTR.xs' */


XS(XS_Crypt__OTR_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_constant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::constant", "sv");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	/* IV		iv;	Uncomment this if you need to return IVs */
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 80 "OTR.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 18 "const-xs.inc"
	type = constant(aTHX_ s, len);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid Crypt::OTR macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined Crypt::OTR macro %s, used",
				   s));
          PUSHs(sv);
          break;
	/* Uncomment this if you need to return IVs
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break; */
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing Crypt::OTR macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 156 "OTR.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'OTR.xs' from 'const-xs.inc' */


XS(XS_Crypt__OTR_crypt_otr_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_init)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_init", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	crypt_otr_init();
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_establish); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_establish)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_establish", "perl_username");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_username = (char *)SvPV_nolen(ST(0));

	crypt_otr_establish(perl_username);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_disconnect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_disconnect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_disconnect", "perl_username");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_username = (char *)SvPV_nolen(ST(0));

	crypt_otr_disconnect(perl_username);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_process_sending); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_process_sending)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_process_sending", "perl_username, perl_message");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
	char*	perl_username = (char *)SvPV_nolen(ST(0));
	char*	perl_message = (char *)SvPV_nolen(ST(1));
#line 77 "OTR.xs"
		RETVAL = 
#line 242 "OTR.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Crypt__OTR_crypt_otr_process_receiving); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_process_receiving)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_process_receiving", "perl_who, perl_message");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	SV *	RETVAL;
	char*	perl_who = (char *)SvPV_nolen(ST(0));
	char*	perl_message = (char *)SvPV_nolen(ST(1));

	RETVAL = crypt_otr_process_receiving(perl_who, perl_message);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Crypt__OTR_crypt_otr_set_keyfile); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_keyfile)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_keyfile", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_keyfile(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_fprfile); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_fprfile)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_fprfile", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_fprfile(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_accountname); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_accountname)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_accountname", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_accountname(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_protocol); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_protocol)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_protocol", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_protocol(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_max_message_size); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_max_message_size)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_max_message_size", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	int	perl_set = (int)SvIV(ST(0));

	crypt_otr_set_max_message_size(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_inject_cb); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_inject_cb)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_inject_cb", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_inject_cb(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_display_cb); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_display_cb)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_display_cb", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_display_cb(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_connected_cb); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_connected_cb)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_connected_cb", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_connected_cb(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_unverified_cb); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_unverified_cb)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_unverified_cb", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_unverified_cb(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_stillconnected_cb); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_stillconnected_cb)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_stillconnected_cb", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_stillconnected_cb(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_disconnected_cb); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_disconnected_cb)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_disconnected_cb", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_disconnected_cb(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_error_cb); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_error_cb)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_error_cb", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_error_cb(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_warning_cb); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_warning_cb)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_warning_cb", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_warning_cb(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_info_cb); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_info_cb)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_info_cb", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_info_cb(perl_set);
    }
    XSRETURN_EMPTY;
}


XS(XS_Crypt__OTR_crypt_otr_set_new_fpr_cb); /* prototype to pass -Wmissing-prototypes */
XS(XS_Crypt__OTR_crypt_otr_set_new_fpr_cb)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Crypt::OTR::crypt_otr_set_new_fpr_cb", "perl_set");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	char*	perl_set = (char *)SvPV_nolen(ST(0));

	crypt_otr_set_new_fpr_cb(perl_set);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Crypt__OTR); /* prototype to pass -Wmissing-prototypes */
XS(boot_Crypt__OTR)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Crypt::OTR::constant", XS_Crypt__OTR_constant, file);
        newXS("Crypt::OTR::crypt_otr_init", XS_Crypt__OTR_crypt_otr_init, file);
        newXS("Crypt::OTR::crypt_otr_establish", XS_Crypt__OTR_crypt_otr_establish, file);
        newXS("Crypt::OTR::crypt_otr_disconnect", XS_Crypt__OTR_crypt_otr_disconnect, file);
        newXS("Crypt::OTR::crypt_otr_process_sending", XS_Crypt__OTR_crypt_otr_process_sending, file);
        newXS("Crypt::OTR::crypt_otr_process_receiving", XS_Crypt__OTR_crypt_otr_process_receiving, file);
        newXS("Crypt::OTR::crypt_otr_set_keyfile", XS_Crypt__OTR_crypt_otr_set_keyfile, file);
        newXS("Crypt::OTR::crypt_otr_set_fprfile", XS_Crypt__OTR_crypt_otr_set_fprfile, file);
        newXS("Crypt::OTR::crypt_otr_set_accountname", XS_Crypt__OTR_crypt_otr_set_accountname, file);
        newXS("Crypt::OTR::crypt_otr_set_protocol", XS_Crypt__OTR_crypt_otr_set_protocol, file);
        newXS("Crypt::OTR::crypt_otr_set_max_message_size", XS_Crypt__OTR_crypt_otr_set_max_message_size, file);
        newXS("Crypt::OTR::crypt_otr_set_inject_cb", XS_Crypt__OTR_crypt_otr_set_inject_cb, file);
        newXS("Crypt::OTR::crypt_otr_set_display_cb", XS_Crypt__OTR_crypt_otr_set_display_cb, file);
        newXS("Crypt::OTR::crypt_otr_set_connected_cb", XS_Crypt__OTR_crypt_otr_set_connected_cb, file);
        newXS("Crypt::OTR::crypt_otr_set_unverified_cb", XS_Crypt__OTR_crypt_otr_set_unverified_cb, file);
        newXS("Crypt::OTR::crypt_otr_set_stillconnected_cb", XS_Crypt__OTR_crypt_otr_set_stillconnected_cb, file);
        newXS("Crypt::OTR::crypt_otr_set_disconnected_cb", XS_Crypt__OTR_crypt_otr_set_disconnected_cb, file);
        newXS("Crypt::OTR::crypt_otr_set_error_cb", XS_Crypt__OTR_crypt_otr_set_error_cb, file);
        newXS("Crypt::OTR::crypt_otr_set_warning_cb", XS_Crypt__OTR_crypt_otr_set_warning_cb, file);
        newXS("Crypt::OTR::crypt_otr_set_info_cb", XS_Crypt__OTR_crypt_otr_set_info_cb, file);
        newXS("Crypt::OTR::crypt_otr_set_new_fpr_cb", XS_Crypt__OTR_crypt_otr_set_new_fpr_cb, file);

    /* Initialisation Section */

#line 41 "OTR.xs"
{
    MY_CXT_INIT;
    /* If any of the fields in the my_cxt_t struct need
     * to be initialised, do it here.
     */

	MY_CXT.userstate = NULL;
	MY_CXT.keyfile = NULL;
	MY_CXT.fprfile = NULL;
	MY_CXT.accountname = NULL;
	MY_CXT.protocol = NULL;
	MY_CXT.max_message_size = 32000; /* This is arbitrary. */

	MY_CXT.inject_cb = NULL;
	MY_CXT.display_cb = NULL;
	MY_CXT.connected_cb = NULL;
	MY_CXT.disconnected_cb = NULL;
	MY_CXT.error_cb = NULL;
	MY_CXT.warning_cb = NULL;
	MY_CXT.info_cb = NULL;
	MY_CXT.new_fpr_cb = NULL;
}

#line 638 "OTR.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

